/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DropsRouteImport } from './routes/drops'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as ShareRouteImport } from './routes/share'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as CanSlugRouteImport } from './routes/can.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DropsRoute = DropsRouteImport.update({
  id: '/drops',
  path: '/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const CanSlugRoute = CanSlugRouteImport.update({
  id: '/can/$slug',
  path: '/can/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drops': typeof DropsRoute
  '/models': typeof ModelsRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/sponsor': typeof SponsorRoute
  '/can/$slug': typeof CanSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drops': typeof DropsRoute
  '/models': typeof ModelsRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/sponsor': typeof SponsorRoute
  '/can/$slug': typeof CanSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drops': typeof DropsRoute
  '/models': typeof ModelsRoute
  '/share': typeof ShareRoute
  '/skills': typeof SkillsRoute
  '/sponsor': typeof SponsorRoute
  '/can/$slug': typeof CanSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drops'
    | '/models'
    | '/share'
    | '/skills'
    | '/sponsor'
    | '/can/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drops'
    | '/models'
    | '/share'
    | '/skills'
    | '/sponsor'
    | '/can/$slug'
  id:
    | '__root__'
    | '/'
    | '/drops'
    | '/models'
    | '/share'
    | '/skills'
    | '/sponsor'
    | '/can/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DropsRoute: typeof DropsRoute
  ModelsRoute: typeof ModelsRoute
  ShareRoute: typeof ShareRoute
  SkillsRoute: typeof SkillsRoute
  SponsorRoute: typeof SponsorRoute
  CanSlugRoute: typeof CanSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drops': {
      id: '/drops'
      path: '/drops'
      fullPath: '/drops'
      preLoaderRoute: typeof DropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/can/$slug': {
      id: '/can/$slug'
      path: '/can/$slug'
      fullPath: '/can/$slug'
      preLoaderRoute: typeof CanSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DropsRoute: DropsRoute,
  ModelsRoute: ModelsRoute,
  ShareRoute: ShareRoute,
  SkillsRoute: SkillsRoute,
  SponsorRoute: SponsorRoute,
  CanSlugRoute: CanSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
